auth0:
  domain: dev-ga7njuw5als2pp77.us.auth0.com
  client-id: EwYBH3Y6AYT1Z@C12SU1e3KUWQqYeNmU
  client-secret: 4g2ofcnB7yP2Y5ZjhiQ_L93aVfr_dR240e50acKcSDeSY7
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: EwYBH3Y6AYT1Z@C12SU1e3KUWQqYeNmU
            client-secret: 4g2ofcnB7yP2Y5ZjhiQ_L93aVfr_dR240e50acKcSDeSY7
            client-name: MindEd
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://${auth0.domain}